# Site settings
title: Triads Go Boink!
email: jesse.fagan@uky.edu
author: Jesse Fagan
description: "A place where I discuss coding and research in social science."
baseurl: ""
url: "http://jfaganuk.github.com"
google_analytics:
animated: true
show_related_posts: true

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
sass:
  compressed: true
